{% set name = "cylp" %}
{% set version = "0.91.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cylp-{{ version }}.tar.gz
  sha256: f026abc29c67a998264db8aa9653fc98c0c38661da68f80ef4b6a0edc117bec0

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
  host:
    - python
    - setuptools
    - cython <3
    - numpy <2.0.0
    - hypothesis
    - pip
    - coin-or-cbc
    - coin-or-utils
    - coin-or-clp
    - coin-or-osi
    - coin-or-cgl
    - coin-or-cbc
  run:
    - python
    - numpy >=1.5.0,<2.0.0
    - scipy >=0.10.0
    - hypothesis
    - coin-or-cbc
    - coin-or-utils
    - coin-or-clp
    - coin-or-osi
    - coin-or-cgl
    - coin-or-cbc

test:
  imports:
    - cylp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/coin-or/cylp
  summary: A Python interface for CLP, CBC, and CGL
  license: EPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nilchia
